### ISSUE TITLE
[Autocomplete] cannot set initial pickList from state.

### ISSUE THREAD

**Issue by DimitriMockelyn** [KleeGroup/focus-components#378]
When you use an autocomplete like this : 

    <AutoComplete loader={listLoader} pickList={this.state.pickList}/>

the pickList is not taken into account.

**Comment by Bernardstanislas** [comment]
This is not an expected behaviour, now you have the `autocompleteFor` in the `form` mixin.
You can have a look at the [`form` example](https://github.com/KleeGroup/focus-components/blob/958a486c196d366f58029b1efe013ce8ea25fc5d/src/common/form/example/index.js#L307) to see how you can use this new feature.
