### ISSUE TITLE
[AdvancedSearch] [orderableColumnList] the same for all scopes

### ISSUE THREAD

**Issue by JoanaDalmeida** [KleeGroup/focus-components#439]
The orderableColumnList prop is the same for all scopes.
In our project the orderable columns are not the same for all scopes.

**Comment by sgoretti** [comment]
Same need on Linkit.

**Comment by pierbrisson** [comment]
:+1:

**Comment by Bernardstanislas** [comment]
As discussed with @JoanaDalmeida, this will be included in the framework but it's considered as a low priority since you can do it easily in your projects directly.
Since the `AdvancedSearch` takes an `orderableColumnList` prop, then you can use the `state` of your wrapping component to change this list on the fly when the `scope` changes.
You can use a `storeBehaviour` to listen to the `scope` changes.

**Comment by Bernardstanislas** [comment]
Closing it since the parent should be responsible for the sortables fields.
