### ISSUE TITLE
[Layout] Menu form appearing if no cartridge

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#592]
# Actual behaviour
![image](https://cloud.githubusercontent.com/assets/14293391/10638084/63344268-7809-11e5-91b1-1fa7081178aa.png)
The thing in red is the form for the MenuLeft
It started appearing when we stopped using the full cartridge and kept only the summary part of it.

Our layout is:
```javascript
let render = FocusCore.application.render;
let Layout = FocusComponents.components.Layout;
let MenuLeft = require('../views/menu');

render(Layout, 'body', {
    props: {MenuLeft}
});
```

# Expected behaviour
![image](https://cloud.githubusercontent.com/assets/14293391/10638121/83664478-7809-11e5-9737-5d2a9926233b.png)

# Versions
0.11 and 0.7.2

**Comment by Bernardstanislas** [comment]
As far as this appears when you shortcut the `header` component, I think you should fix it in your project, with some CSS, since it won't appear if using the component normally.

**Comment by sgoretti** [comment]
How exactly can I add some props to MenuLeft in the layout-initializer you see above?

I tried adding a style prop in the getDefaultProps() of the menu (we have a project-specific menu) so it would be passed to the form, but the formMixin has its own style prop in getDefaultProps that prevented me from doing so.

**Comment by Bernardstanislas** [comment]
Since you are using a form mixin in your custom menu, you won't be able to have a full control on the render method (why a form in a menu btw ?)
I think the best way to do this is to use some SASS, since I think your problem is to access the parent container of your menu content (defined in the `renderContent` method) ?

If it the case, you can access a parent in SASS this way :
```SASS
.your-selector {
    .parent-selector & {
        // some style
    }
}
```
that will be compiled to :
```CSS
.parent-selector .your-selector {
    // some style
}
```
