### ISSUE TITLE
[Question][menu-brand link] Link on application icon

### ISSUE THREAD

**Issue by cbarnay** [KleeGroup/focus-components#691]
The menu mixin defines a div with attribute data-focus="menu-brand" in the top left corner.
We have put the application logo in it with a CSS background.
We would also need to put a link to the home page on this div.
Is there a way to do it?

**Comment by pierr** [comment]
@cbarnay  The menu code is https://github.com/KleeGroup/focus-components/blob/develop/src/components/menu/index.js , you can specify the logo with `<div data-focus='menu-brand'></div`. 
In order to put a link to the homepage, what I suggest is do a pull request with a props dealing with the click on the menu brand `handleMenuBrandClick`, I think this behaviour will be usefull for all projects.
Thanks

**Comment by cbarnay** [comment]
@pierr We are using this menu "component": https://github.com/KleeGroup/focus-components/blob/develop/src/application/menu/index.js
Is it deprecated or for a different usage?

**Comment by Tommass** [comment]
@cbarnay the one in application is deprecated. Please use the one in components.

**Comment by pierr** [comment]
@cbarnay https://github.com/KleeGroup/focus-components/blob/develop/src/components/menu/index.js Can we close this Issue for now. Please reopen it if you need.
