### ISSUE TITLE
[Form][TextArea] value of textarea not set in _getEntity

### ISSUE THREAD

**Issue by JRLK** [KleeGroup/focus-components#792]
In a form I use a `fieldFor` and the domain of my field defines`InputComponent: FocusComponents.common.input.textarea.component`.
The render is OK but the value is always null in `_getEntity`.

`this.refs['contractuel.formuleP1InformationCeleris.formule'].state.value` returns a `SyntheticEvent`

Focus-Core v0.12.0
Focus-Components v0.7.9-rc2

**Comment by pierr** [comment]
I think your field is missing a `ref` because `Textarea` does have a `getValue` method see https://github.com/KleeGroup/focus-components/blob/develop/src/components/input/textarea/index.js#L52
plus you don't use the right `Textarea` component it is in `components/input/textarea` 

Please provide context to your problem, put some of your view code.

**Comment by JRLK** [comment]
@pierr It works with the right `Textarea` (`FocusComponents.components.input.Textarea`).
Thank you

**Comment by pierr** [comment]
@JRLK Cool!
