### ISSUE TITLE
[AutoComplete] No message when no results found

### ISSUE THREAD

**Issue by sgoretti** [KleeGroup/focus-components#918]
### Current behaviour

When I type, if from the start there's no results, nothing indicates that I'm typing for nothing.
![03](https://cloud.githubusercontent.com/assets/14293391/12616246/860a2908-c50a-11e5-8946-9d261d563a7b.PNG)

When I see results and they disappear, I can understand, but I think it would be clearer if we showed the user there are no result.

### Expected behaviour

![04](https://cloud.githubusercontent.com/assets/14293391/12616268/a14090ea-c50a-11e5-90cb-32350eb9891c.PNG)
I used all my amazing paint.net skillz to show what I imagine it should look like.

### Versions

Focus-core: 0.12.3
Focus-components: 0.8.5

**Comment by Bernardstanislas** [comment]
Well in fact this is an expected behaviour, and can be set by the projects themselves. See [there](https://github.com/KleeGroup/focus-components/blob/develop/src%2Fcomponents%2Finput%2Fautocomplete-select%2Fedit.js#L228) to know how to override the options rendering.
You can provide a `renderOptions` props that will be called with the context of the component, so that you can have free access to the `props`, `state` and privates methods.
